name: CD Master Release
on:
  push:
    branches: [ master ]

env:
  CURRENT_STAGE: alpha # -> beta -> release

jobs:
  build-release:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_type: Release
      app_stage: ${{ vars.APP_STAGE || 'alpha' }}

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Real Tag
        id: tag_action
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
          PRERELEASE: ${{ env.CURRENT_STAGE != 'release' }}
          PRERELEASE_SUFFIX: ${{ env.CURRENT_STAGE }}

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Extract Release Notes
        id: release_notes
        run: |
          VERSION="${{ steps.dry_tag.outputs.new_tag }}"
          TEMP='^## \[[0-9].[0-9]'
          VTEMP="^## \[${VERSION#v}"
          awk "/$VTEMP/ && \!f {f=1; next} /$TEMP/ && f {exit} f" CHANGELOG.md > /tmp/release_notes.txt
          if [ ! -s /tmp/release_notes.txt ]; then
            echo "Release notes not found in CHANGELOG.md" > /tmp/release_notes.txt
          fi

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_action.outputs.new_tag }}
          files: artifacts/**/*
          body_path: /tmp/release_notes.txt
          generate_release_notes: true
          make_latest: true
